### ISSUE TITLE
Index.html - Botón "Más Información" lleva a "¿Por dónde empezamos..."

### ISSUE THREAD

**Issue by PedroGalvan** [FraVieMor/EGC-Almacenamiento-de-votos-18-#19]
Será más fácil para el usuario de la web si el botón y el título del apartado se llaman igual.

**Comment by PedroGalvan** [comment]
Ha sido corregido en la rama dev, pero aún hay que comprobar su correcto funcionamiento cuando se despliegue.

**Comment by cristianpoleyJS** [comment]
Actualizado y desplegado.
