### ISSUE TITLE
Index.html - Error en enlace de imagen Estadisticas

### ISSUE THREAD

**Issue by PedroGalvan** [FraVieMor/EGC-Almacenamiento-de-votos-18-#20]
Cuando pulsamos en la imagen de estadisticas se nos redirige a una página no existente "Not Found".
La url del enlace es errónea.

**Comment by PedroGalvan** [comment]
Ha sido corregido en la rama dev, pero aún hay que comprobar su correcto funcionamiento cuando se despliegue.

**Comment by cristianpoleyJS** [comment]
Actualizado y desplegado.
