### ISSUE TITLE
Estadisticas falta comprobar que el usuario es administrador

### ISSUE THREAD

**Issue by AlbertFX91** [FraVieMor/EGC-Almacenamiento-de-votos-18-#21]
Realizar la integración con autenticación, en la que solo podremos entrar en la vista estadisticas si el usuario es un administrador. Aqui una recomendación de implementacion:
1. Index.html -> index.php: Inicialmente (usuario no logueado) no se visualiza la opcion de estadistica.php. En su lugar se ofrece un boton de login.
2. Login: Este boton de login redirigiría a:
   http://auth-egc.azurewebsites.net/?returnUrl=http://http://storage-egc1516.rhcloud.com/
3. Esto nos redirecciona a nuestra web, con un atributo en la url mediante get del siguiente formato
   ?token=test1:29-69-71-9E-3C-B5-EC-68-1C-C9-29-2F-0D-59-DB-3B-91-D4-94-0D-7A-89-86-A8-92-3E-D8-A0-F0-57-7F-19-D2-B3-EA-1B-3C-3A-5F-6F-11-3A-72-78-A4-0F-FF-2C-65-E7-DB-9B-41-87-9F-F8-74-61-B0-31-1E-52-B8-AA
   El parámetro token, está compuesto de un usuario:códigodeautenticación(es otro token).
4. Comprobamos el token mediante autenticacion de nuevo
   GET api/checkToken?token={token}
   ó
   GET api/checkTokenUser?token={token(sin la cadena "usuario:")}&user={user}
5. Si es correcto, guardamos el token en la cookie y de esta forma no tendría que estar repetidamente logueandose.
6. Cuano el token está en la cookie, y se comprueba que es correcto, quiere decir que está logueado, por lo que ya en index.php se le permite la opción de estadisticas.
7. Cuando entra en estadisticas debemos comprobar que el usuario está logueado, de no ser así deberiamos redirigir a la pagina index.php

**Comment by fraviemor** [comment]
Realizados los dos primeros apartados.

**Comment by VctorCanovas** [comment]
Ahora se le indica al usuario sin loguear que debe hacerlo para poder ver las estadísticas. Falta comprobación de si está o no logueado para diferenciar entre cuál de las dos opciones se le muestra.

**Comment by cristianpoleyJS** [comment]
Se han realizado los siguientes añadidos:
- Cambiado index.html para que se vea el boton Log In y Log out cuando corresponda.
- Añadido fichero logout.php para desloguearse.
- Añadida funcionalidad en login.php
- Falta guardar cookies y usarlas para no tener que loguearse.

**Comment by cristianpoleyJS** [comment]
Terminado.
