### ISSUE TITLE
Petición de eliminar los 12 ultimos votos en la votacion 1

### ISSUE THREAD

**Issue by rafaeldrs** [FraVieMor/EGC-Almacenamiento-de-votos-18-#23]
Se pide que se eliminen los 4 primeros votos, ya que el sistema sobre satura las peticiones, y aparentemente no descifra bien los votos.

Un saludo y gracias

**Comment by rafaeldrs** [comment]
O mejor, dejad sólo los 4 primeros votos. Tal y como estaba antes de añadir el resto de votos hoy.

PD: La he cerrado por error

**Comment by cristianpoleyJS** [comment]
Buenas @rafaeldrs 

Ya están borrado los 12 últimos votos.

Saludos.
