### ISSUE TITLE
Recuento: propuesta de método

### ISSUE THREAD

**Issue by rafaeldrs** [FraVieMor/EGC-Almacenamiento-de-votos-18-#26]
Buenas,

Desde recuento os hacemos la petición de crear un nuevo método en vuestro subsistema. 

El objetivo del método sería devolver un JSON con el listado de los IDs de las votaciones que tengan al menos un voto.

Un saludo y muchas gracias.

**Comment by AlbertFX91** [comment]
@rafaeldrs intentaremos realizarlo de cara a la mejora de la memoria el 8 de Febrero

**Comment by cristianpoleyJS** [comment]
Comprobado y desplegado.
