### ISSUE TITLE
Mejoras para Nueva Funcionalidad - Web API y Test

### ISSUE THREAD

**Issue by PedroGalvan** [FraVieMor/EGC-Almacenamiento-de-votos-18-#28]
Se deben realizar cambios para que la API refleje la nueva funcionalidad get_votations.
Además, se tienen que realizar los test para esta misma.

**Comment by PedroGalvan** [comment]
Realizado y pendiente del despliegue

**Comment by AlbertFX91** [comment]
@PedroGalvan Ya está realizado por lo que puede darse por cerrada la Issue.
Cuando la Issue #27 se realize, podremos sacar un nuevo release y enviar a producción
