### ISSUE TITLE
Seguridad en la API

### ISSUE THREAD

**Issue by cristianpoleyJS** [FraVieMor/EGC-Almacenamiento-de-votos-18-#29]
Necesitamos más seguridad en la API Rest de almacenado de votación, debido a que pueden suplantar nuestra identidad.

**Comment by AlbertFX91** [comment]
Estamos trabajando en ello, pronto se le notificará que la incidencia se ha completado.

**Comment by AlbertFX91** [comment]
El error se ha resuelto
