### ISSUE TITLE
Index.html - Error ortográfico

### ISSUE THREAD

**Issue by AlbertFX91** [FraVieMor/EGC-Almacenamiento-de-votos-18-#4]
En el apartado de 'Introducción', hay un error ortográfico. La linea es la siguiente.
'Está subdividido en varios módulos que se encargan de algo diferente dentro de la apliación.'

**Comment by cristianpoleyJS** [comment]
Arreglado, ahora pone "aplicación"

**Comment by AlbertFX91** [comment]
Perfecto
